project2 <- unzip("exdata-data-NEI_data.zip") 
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
library(ggplot2)
subsetdata <- NEI[NEI$fips=="24510" & NEI$type=="ON-ROAD",  ]
aggdata <- aggregate(Emissions ~ year, subsetdata, sum)
g <- ggplot(aggdata,aes(factor(year),Emissions))
graph <- g + geom_bar(stat="identity") + xlab("year") + ylab("Total PM '[2.5]*' Emission") + ggtitle("Emissions From Motor Vehicle-Related Sources")
print(graph)
dev.copy(png, file="plot5.png",width=480, height=480)
dev.off()
